export const MOVIE_SIMPLE = "MOVIE_SIMPLE";
export const MOVIE_EMPTY = "MOVIE_EMPTY";
export const MOVIE_DATA_DETAIL = "MOVIE_DATA_DETAIL";
export const MOVIE_RATING = "MOVIE_RATING";
export const MOVIE_RATING_HEROKU = "MOVIE_RATING_HEROKU";
export const MOVIE_PAGE = "MOVIE_PAGE";
export const MOVIE_GENRE = "MOVIE_GENRE";
export const PAGE_FIRST_LOADING = "PAGE_FIRST_LOADING";
export const MOVIE_PERSONAL = "MOVIE_PERSONAL";
export const MOVIE_PERSONAL_RATING = "MOVIE_PERSONAL_RATING";

export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";